---

- name: Test distribution
  assert:
    that: >
      ( ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 6
      ) or
      ansible_os_family == 'Debian'

- name: Add APT key
  apt_key:
    url: "{{ grafana_debian_repo_key }}"
    state: present
  when: >
    ansible_os_family == 'Debian'

- name: Create Grafana APT repo
  apt_repository:
    repo: "{{ grafana_debian_apt_repository }}"
    state: present
  when: >
    ansible_os_family == 'Debian'

- name: Create Grafana YUM repo file
  yum_repository:
    name: grafana
    description: Internal Grafana repo
    baseurl: "{{ grafana_yumrepo_url }}"
    gpgcheck: 0
    params: "{{ grafana_yumrepo_params }}"
    state: present
  when: ansible_os_family == 'Redhat'


- name: Install Grafana package
  package:
    name: "{{ grafana_pkg }}"
    state: present
  notify:
    - Restart Grafana
  tags:
    - grafana_pkg

- name: Create Grafana config file
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_sysconfig_conf_file }}"
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Create LDAP config file
  template:
    src: ldap.toml.j2
    dest: "{{ grafana_sysconfig_conf_dir ~ '/ldap.toml' }}"
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/sbin/grafana-server | grep cap_net_bind_service
  register: grafana_bind_cap
  failed_when: False
  changed_when: False
  when: grafana_allow_low_port
  tags:
    - grafana_config

- name: Set capability on the binary file to be able to bind to TCP port <1024
  shell: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
  when: grafana_allow_low_port and grafana_bind_cap.rc > 0
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Enable the Grafana service
  service:
    name: "{{ grafana_service }}"
    enabled: yes
  tags:
    - grafana_service

- name: Start the Grafana service
  service:
    name: "{{ grafana_service }}"
    state: started
  register: grafana_service_started
  tags:
    - grafana_service
